import { useMemo } from 'react';
import {
  Activity,
  AlertTriangle,
  Calendar,
  CalendarDays,
  CheckCircle2,
  ChevronRight,
  Clock,
  Droplets,
  Edit3,
  ExternalLink,
  Library,
  Package,
  Stethoscope,
  Syringe,
  Thermometer,
  User,
  Users,
  Wrench,
  XCircle,
  FileText,
  ArrowLeft,
} from 'lucide-react';
import { cn } from '../../lib/utils';
import type {
  Priority,
  SurgeryRequestRecord,
  SurgeryRequestStatus,
  ResourceNavigationPayload,
} from '../../types/surgery';
import { useResourceCatalog } from '../../hooks/useResourceCatalog';
import { flattenSolverAssignments, matchAllocationsToPhaseResource } from '../../lib/phaseSolverAssignments';
import { resolveAssignedResource, toNavigationPayload } from '../../lib/resolveAssignedResource';
import type { ResourceCatalog } from '../../lib/resolveAssignedResource';

type DetailViewProps = {
  record: SurgeryRequestRecord;
  onBack: () => void;
  onEdit: () => void;
  /** Callback when a resource is clicked for navigation */
  onNavigateToResource?: (payload: ResourceNavigationPayload) => void;
};

const statusStyles: Record<SurgeryRequestStatus, string> = {
  DRAFT: 'text-slate-600',
  ESTIMATED: 'text-amber-600',
  PLANNING: 'text-blue-600',
  PLANNED: 'text-emerald-600',
  IN_PROGRESS: 'text-indigo-600',
  DONE: 'text-emerald-700',
  CANCELLED: 'text-rose-600',
};

const statusBadgeStyles: Record<SurgeryRequestStatus, string> = {
  DRAFT: 'bg-slate-100 text-slate-700',
  ESTIMATED: 'bg-amber-100 text-amber-700',
  PLANNING: 'bg-blue-100 text-blue-700',
  PLANNED: 'bg-emerald-100 text-emerald-700',
  IN_PROGRESS: 'bg-indigo-100 text-indigo-700',
  DONE: 'bg-emerald-200 text-emerald-800',
  CANCELLED: 'bg-rose-100 text-rose-700',
};

const statusLabel: Record<SurgeryRequestStatus, string> = {
  DRAFT: 'Draft',
  ESTIMATED: 'Estimated',
  PLANNING: 'Planning in progress',
  PLANNED: 'Scheduled',
  IN_PROGRESS: 'Currently ongoing',
  DONE: 'Completed',
  CANCELLED: 'Cancelled',
};

const statusDescription: Record<SurgeryRequestStatus, string> = {
  DRAFT: 'This request has been saved as a draft and is not yet submitted for planning.',
  ESTIMATED: 'The request has been submitted and is queued for optimization and scheduling.',
  PLANNING: 'The solver is currently processing this request to find the optimal schedule.',
  PLANNED: 'An operating slot and resource assignments have been generated by the solver.',
  IN_PROGRESS: 'This surgery is currently being performed in the operating room.',
  DONE: 'The surgery has been completed successfully.',
  CANCELLED: 'This request has been cancelled and will not be scheduled.',
};

function priorityLabel(p: Priority): string {
  if (p === 'emergency') return 'Emergency';
  if (p === 'mandatory') return 'Mandatory';
  return 'Elective';
}

function formatDateTime(iso?: string): string {
  if (!iso) return '—';
  try {
    const d = new Date(iso);
    if (Number.isNaN(d.getTime())) return iso;
    return new Intl.DateTimeFormat(undefined, {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    }).format(d);
  } catch {
    return iso;
  }
}

function formatDateOnly(iso?: string): string {
  if (!iso) return '—';
  try {
    const d = new Date(iso + 'T12:00:00');
    if (Number.isNaN(d.getTime())) return iso;
    return new Intl.DateTimeFormat(undefined, {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    }).format(d);
  } catch {
    return iso;
  }
}

function formatMinutesToTime(minutes: number): string {
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  return `${h}:${m.toString().padStart(2, '0')}`;
}

function ResourceIcon({ icon }: { icon: string }) {
  if (icon === 'meds') return <Syringe className="text-secondary" size={18} />;
  if (icon === 'blood') return <Droplets className="text-secondary" size={18} />;
  if (icon === 'kit') return <Wrench className="text-secondary" size={18} />;
  if (icon === 'supply') return <Package className="text-secondary" size={18} />;
  return <Thermometer className="text-secondary" size={18} />;
}

function parseDurationToMinutes(duration: string): number {
  let total = 0;
  const dayMatch = duration.match(/(\d+)\s*day/);
  const hourMatch = duration.match(/(\d+)\s*hr/);
  const minMatch = duration.match(/(\d+)\s*min/);
  if (dayMatch) total += parseInt(dayMatch[1], 10) * 24 * 60;
  if (hourMatch) total += parseInt(hourMatch[1], 10) * 60;
  if (minMatch) total += parseInt(minMatch[1], 10);
  return total;
}

function extractAssignmentLabel(item: unknown): string {
  if (item == null) return '';
  if (typeof item === 'string') return item;
  if (typeof item === 'number') return String(item);
  if (typeof item !== 'object') return String(item);

  const obj = item as Record<string, unknown>;
  const nameKeys = [
    'name', 'staffName', 'staff_name', 'employeeName', 'employee_name',
    'displayName', 'display_name', 'fullName', 'full_name', 'firstName', 'lastName',
    'resourceName', 'resource_name', 'label', 'title', 'staff_name',
    'assigned_to', 'assignedTo', 'assignee', 'assigneeName', 'assigned',
  ];
  const idKeys = [
    'id', 'staffId', 'staff_id', 'employeeId', 'employee_id',
    'resourceId', 'resource_id', 'assignmentId', 'assignment_id',
    'solver_id', 'uuid', 'unit_id', 'unitId', 'assigned_unit_id',
  ];
  const roleKeys = [
    'role', 'roleType', 'role_type', 'position', 'specialty', 'type',
    'resource_type', 'resourceType', 'category',
  ];

  const pickStr = (keys: string[]): string => {
    for (const k of keys) {
      const v = obj[k];
      if (typeof v === 'string' && v.trim()) return v.trim();
      if (typeof v === 'number') return String(v);
    }
    return '';
  };

  const name = pickStr(nameKeys);
  const id = pickStr(idKeys);
  const role = pickStr(roleKeys);

  const parts: string[] = [];
  if (name) parts.push(name);
  if (role && role !== name) parts.push(role);
  if (id && id !== name && id !== role) parts.push(`#${id}`);

  if (parts.length > 0) return parts.join(' • ');

  const allStrings = Object.values(obj)
    .flatMap((v): string[] => {
      if (typeof v === 'string' && v.trim()) return [v.trim()];
      if (typeof v === 'number') return [String(v)];
      return [];
    });
  if (allStrings.length > 0) return Array.from(new Set(allStrings)).join(' / ');

  try {
    return JSON.stringify(obj);
  } catch {
    return String(obj);
  }
}

function extractAssignmentTooltip(item: unknown): string {
  try {
    return typeof item === 'object' && item != null
      ? JSON.stringify(item, null, 2)
      : '';
  } catch {
    return '';
  }
}

function isPlainObject(v: unknown): v is Record<string, unknown> {
  return v != null && typeof v === 'object' && !Array.isArray(v);
}

/** Extract resource ID from an assignment object - tries multiple field names and nested structures */
function extractResourceId(item: unknown): string | null {
  if (typeof item === 'string') return item;
  if (typeof item === 'number') return String(item);
  
  if (item && typeof item === 'object') {
    const obj = item as Record<string, unknown>;
    
    // Direct ID keys to check
    const idKeys = [
      'id', 'staffId', 'staff_id', 'employeeId', 'employee_id', 
      'resourceId', 'resource_id', 'unit_id', 'unitId', 
      'assigned_unit_id', 'assigned', 'assignedTo', 'assigned_to',
      'member_id', 'memberId', 'solver_id', 'solverId',
    ];
    
    for (const k of idKeys) {
      const val = obj[k];
      if (val && typeof val === 'string') return val;
      if (val && typeof val === 'number') return String(val);
    }
    
    // Check nested objects (e.g., { assignment: { id: "..." } })
    const nestedKeys = ['assignment', 'resource', 'staff', 'member', 'unit'];
    for (const nk of nestedKeys) {
      if (obj[nk] && typeof obj[nk] === 'object') {
        const nested = extractResourceId(obj[nk]);
        if (nested) return nested;
      }
    }
  }
  return null;
}

/** Extract pool ID from an assignment object */
function extractPoolId(item: unknown): string | null {
  if (item && typeof item === 'object') {
    const obj = item as Record<string, unknown>;
    const poolIdKeys = ['pool_id', 'poolId', 'resourcePoolId', 'resource_pool_id'];
    for (const k of poolIdKeys) {
      if (obj[k] && typeof obj[k] === 'string') return obj[k] as string;
    }
  }
  return null;
}

type NormalizedAssignment = {
  label: string;
  tooltip: string;
  resourceId: string | null;
  poolId: string | null;
  rawData: unknown;
};

type AllocatedAssignee = NormalizedAssignment & { solverRoleKey: string };

function AllocatedAssigneeChips({
  assignees,
  resourceCatalog,
  plannedStartIso,
  referenceCode,
  onNavigateToResource,
}: {
  assignees: AllocatedAssignee[];
  resourceCatalog: ResourceCatalog;
  plannedStartIso?: string;
  referenceCode: string;
  onNavigateToResource?: (payload: ResourceNavigationPayload) => void;
}) {
  return (
    <div className="flex flex-wrap gap-2">
      {assignees.map((a, idx) => {
        const roleLabel = a.solverRoleKey.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
        const extraIds: string[] = [];
        if (a.rawData && typeof a.rawData === 'object') {
          const raw = a.rawData as Record<string, unknown>;
          for (const key of [
            'unit_id', 'unitId', 'assigned', 'assigned_unit_id',
            'staff_id', 'staffId', 'employee_id', 'employeeId',
            'id', 'resourceId', 'resource_id', 'pool_id', 'poolId',
          ]) {
            const val = raw[key];
            if (val != null && (typeof val === 'string' || typeof val === 'number')) {
              extraIds.push(String(val));
            }
          }
        }
        const resolved = resolveAssignedResource(
          [a.resourceId, a.poolId, a.label, ...extraIds],
          a.solverRoleKey,
          resourceCatalog,
        );
        const displayName = resolved?.displayName || a.label;
        const displayTitle = resolved?.subtitle || '';
        const isNavigable = Boolean(onNavigateToResource && resolved);

        const handleAssigneeClick = () => {
          if (!onNavigateToResource || !resolved) return;
          onNavigateToResource(toNavigationPayload(resolved, {
            role: roleLabel,
            surgeryStartTime: plannedStartIso,
            surgeryReference: referenceCode,
          }));
        };

        const Wrapper = isNavigable ? 'button' : 'span';

        return (
          <Wrapper
            key={`${a.solverRoleKey}-${idx}-${displayName}`}
            type={isNavigable ? 'button' : undefined}
            onClick={isNavigable ? handleAssigneeClick : undefined}
            className={cn(
              'inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md text-[11px] font-bold border transition-all',
              isNavigable
                ? 'bg-emerald-50 text-emerald-800 border-emerald-200 hover:bg-emerald-100 hover:border-emerald-300 cursor-pointer group'
                : 'bg-emerald-50/80 text-emerald-900 border-emerald-100',
            )}
            title={
              resolved
                ? `${displayName}${displayTitle ? ` — ${displayTitle}` : ''}`
                : displayName
            }
          >
            {resolved?.kind === 'nh-pool' ? (
              <Wrench size={12} className="shrink-0 text-emerald-600" />
            ) : (
              <User size={12} className="shrink-0 text-emerald-600" />
            )}
            <span className="truncate max-w-[12rem]">{displayName}</span>
            {displayTitle && (
              <span className="text-[10px] text-slate-500 font-normal">({displayTitle})</span>
            )}
            {isNavigable && (
              <ExternalLink className="w-3 h-3 text-emerald-500 opacity-0 group-hover:opacity-100 transition-opacity shrink-0" />
            )}
          </Wrapper>
        );
      })}
    </div>
  );
}

function normalizeAssignments(value: unknown): NormalizedAssignment[] {
  if (value == null || value === '') return [];

  if (Array.isArray(value)) {
    const flat: NormalizedAssignment[] = [];
    for (const item of value) {
      if (isPlainObject(item) && !Array.isArray(item)) {
        const hasNameLike = Object.keys(item).some((k) => {
          const kl = k.toLowerCase();
          return (
            kl.includes('name') || kl.includes('label') || kl.includes('title') ||
            kl.includes('id') || kl === 'role' || kl === 'type'
          );
        });
        if (hasNameLike) {
          const label = extractAssignmentLabel(item);
          const tooltip = extractAssignmentTooltip(item);
          const resourceId = extractResourceId(item);
          const poolId = extractPoolId(item);
          if (label) flat.push({ label, tooltip, resourceId, poolId, rawData: item });
        } else {
          flat.push(...normalizeAssignments(Object.entries(item)));
        }
      } else if (Array.isArray(item)) {
        flat.push(...normalizeAssignments(item));
      } else {
        const label = extractAssignmentLabel(item);
        const tooltip = extractAssignmentTooltip(item);
        const resourceId = extractResourceId(item);
        if (label) flat.push({ label, tooltip, resourceId, poolId: null, rawData: item });
      }
    }
    return flat;
  }

  if (isPlainObject(value)) {
    const keys = Object.keys(value);
    const hasNameLike = keys.some((k) => {
      const kl = k.toLowerCase();
      return (
        kl.includes('name') || kl.includes('label') || kl.includes('title') ||
        kl.includes('id') || kl === 'role' || kl === 'type'
      );
    });
    if (hasNameLike) {
      const label = extractAssignmentLabel(value);
      const tooltip = extractAssignmentTooltip(value);
      const resourceId = extractResourceId(value);
      const poolId = extractPoolId(value);
      return label ? [{ label, tooltip, resourceId, poolId, rawData: value }] : [];
    }
    const flat: NormalizedAssignment[] = [];
    for (const [k, v] of Object.entries(value)) {
      const subItems = normalizeAssignments(v);
      if (subItems.length > 0) {
        for (const s of subItems) {
          const newLabel = `${k.replace(/_/g, ' ')}: ${s.label}`;
          flat.push({
            label: newLabel,
            tooltip: s.tooltip || extractAssignmentTooltip(v),
            resourceId: s.resourceId,
            poolId: s.poolId,
            rawData: v,
          });
        }
      } else {
        const label = extractAssignmentLabel(v);
        const resourceId = extractResourceId(v);
        const poolId = extractPoolId(v);
        if (label) {
          flat.push({
            label: `${k.replace(/_/g, ' ')}: ${label}`,
            tooltip: extractAssignmentTooltip(v),
            resourceId,
            poolId,
            rawData: v,
          });
        }
      }
    }
    return flat;
  }

  const label = extractAssignmentLabel(value);
  const tooltip = extractAssignmentTooltip(value);
  const resourceId = extractResourceId(value);
  return label ? [{ label, tooltip, resourceId, poolId: null, rawData: value }] : [];
}

type PhaseMeta = {
  key: 'preOp' | 'operative' | 'postOp' | 'sterilization' | 'recovery';
  label: string;
  description: string;
  accent: string;
};

const PHASE_META: PhaseMeta[] = [
  { key: 'preOp', label: 'Pre-operative', description: 'Initial stabilization and vitals monitoring before the procedure.', accent: 'bg-secondary-container/15 border-secondary-container/40' },
  { key: 'operative', label: 'Operative', description: 'Core surgical procedure and anesthesia administration.', accent: 'bg-primary-container/10 border-primary-container/30' },
  { key: 'postOp', label: 'Post-operative', description: 'Emergence from anesthesia and initial recovery.', accent: 'bg-tertiary-container/15 border-tertiary-container/40' },
  { key: 'sterilization', label: 'Sterilization & Turnover', description: 'Room cleanup and sterilization between surgeries.', accent: 'bg-surface-container-lowest border-outline-variant/60' },
  { key: 'recovery', label: 'Recovery', description: 'Extended post-surgical care and patient monitoring.', accent: 'bg-secondary/5 border-secondary/20' },
];

export function SurgeryRequestDetailView({ record, onBack, onEdit, onNavigateToResource }: DetailViewProps) {
  const { data, status, planResult, referenceCode, updatedAt } = record;
  const resourceCatalog = useResourceCatalog();

  const shortages = useMemo(() => data.resources.filter((r) => r.status === 'shortage'), [data.resources]);

  const hasPlanResult = ['PLANNED', 'IN_PROGRESS', 'DONE'].includes(status)
    && Boolean(planResult && (planResult.result?.planned_start || planResult.result?.resources_assigned));
  const plannedStartIso = planResult?.result?.planned_start as string | undefined;
  const resourcesAssigned = (planResult?.result?.resources_assigned ?? {}) as Record<string, unknown>;
  const assignedEntries = Object.entries(resourcesAssigned);

  const flatSolverAssignments = useMemo(
    () => (hasPlanResult ? flattenSolverAssignments(resourcesAssigned) : []),
    [hasPlanResult, resourcesAssigned],
  );

  const phaseSummaries = useMemo(() => {
    const phaseOrder: PhaseMeta['key'][] = ['preOp', 'operative', 'postOp', 'sterilization', 'recovery'];
    let cumulativeOffset = 0;
    return phaseOrder.map((phaseKey) => {
      const meta = PHASE_META.find((m) => m.key === phaseKey)!;
      const phase = data.phases[phaseKey];
      const durationMinutes = parseDurationToMinutes(phase.duration);
      const startOffset = cumulativeOffset;
      cumulativeOffset += durationMinutes;
      const resources = phase.resources.map((resource) => {
        const matchedEntries = matchAllocationsToPhaseResource(phaseKey, resource, flatSolverAssignments);
        const allocated: AllocatedAssignee[] = matchedEntries.flatMap((entry) =>
          normalizeAssignments(entry.value).map((assignee) => ({
            ...assignee,
            solverRoleKey: entry.solverRoleKey,
          })),
        );
        return { ...resource, allocated };
      });
      return {
        ...meta,
        duration: phase.duration,
        durationMinutes,
        startOffset,
        resources,
        icuProbability: phase.icuProbability,
      };
    });
  }, [data.phases, flatSolverAssignments]);

  const totalDurationMinutes = phaseSummaries.reduce((acc, ph) => acc + ph.durationMinutes, 0);

  return (
    <div className="min-h-[calc(100vh-7rem)] pb-16">
      {/* Sticky Header */}
      <div className="sticky top-0 z-40 bg-surface-container-lowest/95 backdrop-blur border-b border-slate-200 mb-8 -mx-6 lg:-mx-8 px-6 lg:px-8 pt-6 pb-6">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div className="flex items-center gap-4 flex-wrap">
            <button
              type="button"
              onClick={onBack}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-white border border-slate-200 text-slate-700 text-sm font-bold hover:bg-slate-50 transition-colors"
            >
              <ArrowLeft size={16} />
              Back to list
            </button>
            <div className="flex items-center gap-1.5 text-sm text-slate-500 font-medium">
              <span>Surgery requests</span>
              <ChevronRight size={14} />
              <span className="text-on-surface font-semibold">Request details</span>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <span className={cn(
              'inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold uppercase tracking-wider',
              statusBadgeStyles[status],
            )}>
              <span className={cn(
                'w-1.5 h-1.5 rounded-full',
                (status === 'PLANNING' || status === 'IN_PROGRESS') && 'animate-pulse',
                status === 'DRAFT' && 'bg-slate-600',
                status === 'ESTIMATED' && 'bg-amber-600',
                status === 'PLANNING' && 'bg-blue-600',
                status === 'PLANNED' && 'bg-emerald-600',
                status === 'IN_PROGRESS' && 'bg-indigo-600',
                status === 'DONE' && 'bg-emerald-700',
                status === 'CANCELLED' && 'bg-rose-600',
              )} />
              {statusLabel[status]}
            </span>
            <button
              type="button"
              onClick={onEdit}
              disabled={status === 'CANCELLED'}
              className={cn(
                'inline-flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-bold transition-colors shadow-sm',
                status === 'CANCELLED'
                  ? 'bg-slate-100 text-slate-400 cursor-not-allowed'
                  : 'bg-primary text-on-primary hover:opacity-90 shadow-primary/20',
              )}
            >
              <Edit3 size={16} />
              {status === 'DRAFT' ? 'Continue editing' : 'Edit request'}
            </button>
          </div>
        </div>

        {/* Title row */}
        <div className="mt-6 flex flex-wrap items-end justify-between gap-6">
          <div className="min-w-0">
            <div className="flex items-center gap-3 mb-2 flex-wrap">
              <h1 className="text-3xl font-extrabold tracking-tight text-on-surface font-headline truncate">
                {data.patientName?.trim() || 'Unnamed patient'}
              </h1>
              <span className="text-xs font-mono font-bold bg-surface-container px-2 py-1 rounded text-outline">
                {referenceCode}
              </span>
            </div>
            <p className="text-slate-600 font-medium">
              {data.operationType?.trim() || 'Procedure not specified'}
              {data.primarySurgeon?.trim() ? ` • ${data.primarySurgeon}` : ''}
            </p>
          </div>
          <div className="text-sm text-slate-500">
            Last updated <span className="font-semibold text-on-surface">{formatDateTime(updatedAt)}</span>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 max-w-7xl mx-auto">
        {/* Left column */}
        <div className="lg:col-span-8 space-y-8">
          {/* Plan Results Banner */}
          {hasPlanResult && (
            <section className="bg-gradient-to-br from-emerald-50 via-white to-emerald-50 border-2 border-emerald-200 rounded-2xl p-8 shadow-sm overflow-hidden relative">
              <div className="absolute top-0 right-0 w-40 h-40 bg-emerald-100/40 rounded-full -translate-y-1/2 translate-x-1/3 blur-3xl" />
              <div className="relative z-10 flex items-start gap-4 flex-wrap">
                <div className="w-12 h-12 rounded-xl bg-emerald-500 text-white flex items-center justify-center shrink-0 shadow-lg shadow-emerald-500/30">
                  <CalendarDays size={24} />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1 flex-wrap">
                    <h2 className="text-xl font-bold text-emerald-900 font-headline">Surgery Scheduled</h2>
                    <span className="text-[10px] font-bold uppercase tracking-wider bg-emerald-100 text-emerald-700 px-2 py-0.5 rounded">
                      {statusLabel[status]}
                    </span>
                  </div>
                  <p className="text-sm text-emerald-800/80 font-medium mb-4">
                    Resources have been allocated and the surgery is ready for execution.
                  </p>

                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    <div className="bg-white rounded-xl border border-emerald-100 p-5 md:col-span-1">
                      <p className="text-[10px] font-bold uppercase tracking-wider text-emerald-700/70 mb-2">
                        Assigned start time
                      </p>
                      <p className="text-2xl font-extrabold text-emerald-900 font-headline">
                        {formatDateTime(plannedStartIso)}
                      </p>
                      {plannedStartIso && (
                        <p className="text-xs text-emerald-800/70 mt-1 font-medium">
                          Expected end ~ {formatDateTime(new Date(new Date(plannedStartIso).getTime() + totalDurationMinutes * 60 * 1000).toISOString())}
                        </p>
                      )}
                    </div>
                    <div className="bg-white rounded-xl border border-emerald-100 p-5 md:col-span-2">
                      <p className="text-[10px] font-bold uppercase tracking-wider text-emerald-700/70 mb-3">
                        Allocated Resources ({assignedEntries.length} {assignedEntries.length === 1 ? 'role' : 'roles'})
                      </p>
                      {assignedEntries.length === 0 ? (
                        <p className="text-sm text-emerald-800/70 font-medium">No resource assignments from solver.</p>
                      ) : (
                        <div className="space-y-3">
                          {assignedEntries.map(([role, value]) => {
                            const roleLabel = String(role).replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
                            const assignees = normalizeAssignments(value);
                            return (
                              <div key={role} className="bg-emerald-50/50 rounded-lg p-3 border border-emerald-100/60">
                                <div className="flex items-center gap-2 mb-2">
                                  <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-emerald-600 text-white text-xs font-bold shadow-sm">
                                    <Users size={12} />
                                    {roleLabel}
                                  </span>
                                  <span className="text-[10px] text-emerald-600 font-semibold">
                                    {assignees.length} allocated
                                  </span>
                                </div>
                                {assignees.length === 0 ? (
                                  <span className="text-xs text-emerald-800/60 italic">
                                    Pending assignment details
                                  </span>
                                ) : (
                                  <div className="flex flex-wrap gap-2">
                                    {assignees.map((a, idx) => {
                                      const extraIds: string[] = [];
                                      if (a.rawData && typeof a.rawData === 'object') {
                                        const raw = a.rawData as Record<string, unknown>;
                                        for (const key of [
                                          'unit_id', 'unitId', 'assigned', 'assigned_unit_id',
                                          'staff_id', 'staffId', 'employee_id', 'employeeId',
                                          'id', 'resourceId', 'resource_id', 'pool_id', 'poolId',
                                        ]) {
                                          const val = raw[key];
                                          if (val != null && (typeof val === 'string' || typeof val === 'number')) {
                                            extraIds.push(String(val));
                                          }
                                        }
                                      }
                                      const resolved = resolveAssignedResource(
                                        [a.resourceId, a.poolId, a.label, ...extraIds],
                                        role,
                                        resourceCatalog,
                                      );
                                      const displayName = resolved?.displayName || a.label;
                                      const displayTitle = resolved?.subtitle || '';
                                      const isNavigable = Boolean(onNavigateToResource && resolved);

                                      const handleAssigneeClick = () => {
                                        if (!onNavigateToResource || !resolved) return;
                                        onNavigateToResource(toNavigationPayload(resolved, {
                                          role: roleLabel,
                                          surgeryStartTime: plannedStartIso,
                                          surgeryReference: referenceCode,
                                        }));
                                      };

                                      const Wrapper = isNavigable ? 'button' : 'span';

                                      return (
                                        <Wrapper
                                          key={`${role}-${idx}-${displayName}`}
                                          type={isNavigable ? 'button' : undefined}
                                          onClick={isNavigable ? handleAssigneeClick : undefined}
                                          className={cn(
                                            'inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm font-semibold border shadow-sm transition-all',
                                            isNavigable
                                              ? 'bg-white text-indigo-700 border-indigo-200 hover:bg-indigo-50 hover:border-indigo-300 hover:shadow-md cursor-pointer group'
                                              : 'bg-white text-emerald-900 border-emerald-200',
                                          )}
                                          title={
                                            resolved
                                              ? `${displayName}${displayTitle ? ` — ${displayTitle}` : ''}\nOpen ${resolved.kind === 'staff' ? 'staff profile' : resolved.kind === 'hr-pool' ? 'staff pool' : 'equipment pool'}`
                                              : displayName
                                          }
                                        >
                                          {resolved?.kind === 'nh-pool' ? (
                                            <Wrench size={14} className={cn('shrink-0', isNavigable ? 'text-indigo-500' : 'text-emerald-600')} />
                                          ) : (
                                            <User size={14} className={cn('shrink-0', isNavigable ? 'text-indigo-500' : 'text-emerald-600')} />
                                          )}
                                          <span className="truncate max-w-[14rem]">{displayName}</span>
                                          {displayTitle && (
                                            <span className="text-[10px] text-slate-500 font-normal">({displayTitle})</span>
                                          )}
                                          {isNavigable && (
                                            <ExternalLink className="w-3 h-3 text-indigo-400 opacity-0 group-hover:opacity-100 transition-opacity shrink-0" />
                                          )}
                                        </Wrapper>
                                      );
                                    })}
                                  </div>
                                )}
                              </div>
                            );
                          })}
                        </div>
                      )}
                    </div>
                  </div>

                  {planResult?.result && (
                    <details className="mt-5 rounded-xl border border-emerald-100 bg-white/60 overflow-hidden">
                      <summary className="cursor-pointer px-4 py-2.5 text-[10px] font-bold uppercase tracking-wider text-emerald-700/70 hover:bg-emerald-50/50 transition-colors select-none list-none">
                        <span className="inline-flex items-center gap-1.5">
                          <Wrench size={12} />
                          Inspect raw solver response (debug)
                        </span>
                      </summary>
                      <pre className="px-4 pb-4 pt-1 overflow-x-auto text-[11px] leading-relaxed font-mono text-slate-700 bg-slate-900/5">
                        {JSON.stringify(planResult.result, null, 2)}
                      </pre>
                    </details>
                  )}
                </div>
              </div>
            </section>
          )}

          {/* Status summary */}
          {!hasPlanResult && (
            <section className={cn(
              'rounded-2xl p-6 flex items-start gap-4 border',
              status === 'CANCELLED' ? 'bg-rose-50 border-rose-200' : 'bg-surface-container-low border-surface-container-high',
            )}>
              {status === 'CANCELLED' ? (
                <XCircle className="text-rose-600 shrink-0" size={28} />
              ) : status === 'PLANNING' ? (
                <div className="relative shrink-0">
                  <Activity className="text-blue-600 animate-pulse" size={28} />
                </div>
              ) : status === 'DRAFT' ? (
                <FileText className="text-slate-500 shrink-0" size={28} />
              ) : (
                <Clock className={cn('shrink-0', statusStyles[status])} size={28} />
              )}
              <div>
                <h3 className={cn('font-bold text-lg', status === 'CANCELLED' ? 'text-rose-900' : 'text-on-surface')}>
                  {statusLabel[status]}
                </h3>
                <p className={cn('text-sm mt-1', status === 'CANCELLED' ? 'text-rose-800/80' : 'text-outline')}>
                  {statusDescription[status]}
                </p>
              </div>
            </section>
          )}

          {/* Patient & Scheduling */}
          <section className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden">
            <div className="px-8 py-6 border-b border-slate-100 bg-surface-container-lowest/50">
              <div className="flex items-center gap-3">
                <span className="w-10 h-10 rounded-xl bg-primary-container/25 flex items-center justify-center shrink-0">
                  <User className="text-primary" size={22} />
                </span>
                <div>
                  <h2 className="text-xl font-bold tracking-tight text-on-surface font-headline">Patient & Scheduling</h2>
                  <p className="text-sm text-slate-500 mt-0.5">Identity, oversight, and time-window constraints.</p>
                </div>
              </div>
            </div>
            <div className="p-8">
              <dl className="grid grid-cols-1 md:grid-cols-2 gap-x-12 gap-y-8">
                <div>
                  <dt className="text-[11px] font-black uppercase tracking-widest text-slate-400 mb-1.5">Patient name</dt>
                  <dd className="text-lg font-semibold text-on-surface">{data.patientName?.trim() || '—'}</dd>
                </div>
                <div>
                  <dt className="text-[11px] font-black uppercase tracking-widest text-slate-400 mb-1.5">Procedure</dt>
                  <dd className="text-lg font-semibold text-on-surface">{data.operationType?.trim() || '—'}</dd>
                </div>
                <div>
                  <dt className="text-[11px] font-black uppercase tracking-widest text-slate-400 mb-1.5">Attending surgeon</dt>
                  <dd className="text-lg font-semibold text-on-surface">{data.primarySurgeon?.trim() || '—'}</dd>
                </div>
                <div>
                  <dt className="text-[11px] font-black uppercase tracking-widest text-slate-400 mb-1.5">Department</dt>
                  <dd className="text-lg font-semibold text-on-surface">{data.department?.trim() || '—'}</dd>
                </div>
                <div>
                  <dt className="text-[11px] font-black uppercase tracking-widest text-slate-400 mb-1.5">Priority</dt>
                  <dd>
                    <span className={cn(
                      'inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold',
                      data.priority === 'emergency' && 'bg-error-container text-on-error-container',
                      data.priority === 'mandatory' && 'bg-secondary-container/30 text-secondary',
                      data.priority === 'elective' && 'bg-surface-container-high text-on-surface-variant',
                    )}>
                      {data.priority === 'emergency' && <AlertTriangle size={12} />}
                      {priorityLabel(data.priority)}
                    </span>
                  </dd>
                </div>
                <div>
                  <dt className="text-[11px] font-black uppercase tracking-widest text-slate-400 mb-1.5">Infection status</dt>
                  <dd className="text-lg font-semibold text-on-surface flex items-center gap-2">
                    <CheckCircle2 className="text-tertiary shrink-0" size={18} />
                    {data.infectionStatus || 'Not specified'}
                  </dd>
                </div>
                <div className="md:col-span-2 bg-surface-container-low rounded-xl p-5 border border-surface-container-high">
                  <div className="flex items-center gap-2 mb-3">
                    <Calendar className="text-slate-500" size={18} />
                    <span className="text-[11px] font-black uppercase tracking-widest text-slate-500">Optimal time window</span>
                  </div>
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                    <div className="bg-white rounded-lg p-4 border border-slate-100">
                      <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-1">Earliest</p>
                      <p className="text-lg font-bold text-on-surface">{formatDateOnly(data.earliestDate)}</p>
                      <p className="text-xs text-slate-500 mt-0.5">{data.earliestDateTime?.split('T')[1] || '00:00'}</p>
                    </div>
                    <div className="flex items-center justify-center text-slate-300">
                      <div className="flex items-center gap-2">
                        <div className="h-0.5 w-8 bg-slate-200 rounded" />
                        <ChevronRight size={16} />
                        <div className="h-0.5 w-8 bg-slate-200 rounded" />
                      </div>
                    </div>
                    <div className="bg-white rounded-lg p-4 border border-rose-100">
                      <p className="text-[10px] font-bold uppercase tracking-wider text-rose-500 mb-1">Deadline</p>
                      <p className="text-lg font-bold text-rose-900">{formatDateOnly(data.endDate)}</p>
                      <p className="text-xs text-rose-500/80 mt-0.5">{data.endDateTime?.split('T')[1] || '23:59'}</p>
                    </div>
                  </div>
                </div>
              </dl>
            </div>
          </section>

          {/* Phase Resource Configuration */}
          <section className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden">
            <div className="px-8 py-6 border-b border-slate-100 bg-surface-container-lowest/50">
              <div className="flex items-center justify-between gap-4 flex-wrap">
                <div className="flex items-center gap-3">
                  <span className="w-10 h-10 rounded-xl bg-primary-container/25 flex items-center justify-center shrink-0">
                    <Activity className="text-primary" size={22} />
                  </span>
                  <div>
                    <h2 className="text-xl font-bold tracking-tight text-on-surface font-headline">Phase Resource Configuration</h2>
                    <p className="text-sm text-slate-500 mt-0.5">
                      Staff, rooms, and equipment across the surgical lifecycle.
                      Total estimated duration: <span className="font-bold text-on-surface">{totalDurationMinutes} min ({formatMinutesToTime(totalDurationMinutes)})</span>
                    </p>
                  </div>
                </div>
              </div>
            </div>

            {/* Timeline strip */}
            <div className="px-8 py-6 bg-surface-container-lowest/30 border-b border-slate-100">
              <div className="relative h-4 rounded-full bg-surface-container-high overflow-hidden flex">
                {phaseSummaries.map((phase) => {
                  const pct = totalDurationMinutes > 0 ? (phase.durationMinutes / totalDurationMinutes) * 100 : 20;
                  const color =
                    phase.key === 'preOp' ? 'bg-secondary-container' :
                    phase.key === 'operative' ? 'bg-primary' :
                    phase.key === 'postOp' ? 'bg-tertiary-container' :
                    phase.key === 'sterilization' ? 'bg-outline-variant' :
                    'bg-secondary/70';
                  return (
                    <div
                      key={phase.key}
                      className={cn('h-full first:rounded-l-full last:rounded-r-full', color)}
                      style={{ width: `${pct}%` }}
                      title={`${phase.label} — ${phase.duration}`}
                    />
                  );
                })}
              </div>
              <div className="grid grid-cols-5 gap-2 mt-3">
                {phaseSummaries.map((phase) => (
                  <div key={phase.key} className="flex items-center gap-2 min-w-0">
                    <span className={cn(
                      'w-2.5 h-2.5 rounded shrink-0',
                      phase.key === 'preOp' ? 'bg-secondary-container' :
                      phase.key === 'operative' ? 'bg-primary' :
                      phase.key === 'postOp' ? 'bg-tertiary-container' :
                      phase.key === 'sterilization' ? 'bg-outline-variant' :
                      'bg-secondary/70',
                    )} />
                    <span className="text-[10px] font-bold text-slate-600 truncate">{phase.label}</span>
                  </div>
                ))}
              </div>
            </div>

            <div className="p-8 space-y-5">
              {phaseSummaries.map((phase) => (
                <div
                  key={phase.key}
                  className={cn(
                    'rounded-xl border overflow-hidden',
                    phase.accent,
                  )}
                >
                  <div className="px-6 py-4 flex flex-wrap items-center justify-between gap-3 border-b border-black/5">
                    <div>
                      <div className="flex items-center gap-2">
                        <h3 className="font-bold text-on-surface">{phase.label}</h3>
                        <span className="text-[10px] font-bold uppercase tracking-wider text-outline/70 bg-white/70 px-2 py-0.5 rounded border border-black/5">
                          Phase starts at T+{formatMinutesToTime(phase.startOffset)}
                        </span>
                      </div>
                      <p className="text-xs text-slate-600 mt-0.5">{phase.description}</p>
                    </div>
                    <div className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white border border-black/5">
                      <Clock size={14} className="text-slate-500" />
                      <span className="text-sm font-bold text-on-surface">{phase.duration}</span>
                    </div>
                  </div>
                  <div className="px-6 py-5 bg-white/40">
                    {phase.resources.length === 0 ? (
                      <p className="text-sm text-slate-400 italic">No resources configured for this phase.</p>
                    ) : (
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                        {phase.resources.map((res, idx) => (
                          <div
                            key={`${phase.key}-${idx}-${res.name}`}
                            className="bg-white rounded-lg border border-slate-100 p-4 hover:shadow-sm transition-shadow"
                          >
                            <div className="flex items-start justify-between gap-3">
                              <div className="flex items-start gap-3 min-w-0">
                                <div className="w-9 h-9 rounded-lg bg-tertiary-container/15 text-tertiary flex items-center justify-center shrink-0">
                                  <Stethoscope size={16} />
                                </div>
                                <div className="min-w-0">
                                  <p className="font-bold text-sm text-on-surface truncate">{res.name}</p>
                                  {res.roles && res.roles.length > 0 && res.roles[0] !== res.name && (
                                    <p className="text-[11px] text-slate-500 mt-0.5">
                                      Role: {res.roles.join(', ')}
                                    </p>
                                  )}
                                  {res.allocated.length > 0 && (
                                    <div className="mt-2">
                                      <AllocatedAssigneeChips
                                        assignees={res.allocated}
                                        resourceCatalog={resourceCatalog}
                                        plannedStartIso={plannedStartIso}
                                        referenceCode={referenceCode}
                                        onNavigateToResource={onNavigateToResource}
                                      />
                                    </div>
                                  )}
                                </div>
                              </div>
                              <span className="text-sm font-black px-2.5 py-1 rounded-md bg-primary/10 text-primary shrink-0">
                                ×{res.count}
                              </span>
                            </div>
                            <div className="mt-3 pt-3 border-t border-slate-100/70 flex items-center justify-between">
                              <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">
                                Required window
                              </span>
                              <span className="text-xs font-bold text-on-surface-variant">
                                T+{formatMinutesToTime(res.startTime ?? 0)} — T+{formatMinutesToTime(res.endTime ?? phase.durationMinutes)}
                              </span>
                            </div>
                            {(res.assignments ?? []).length > 0 && (
                              <div className="mt-3 pt-3 border-t border-slate-100/70">
                                <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-2 block">
                                  Manual assignments
                                </span>
                                <div className="flex flex-wrap gap-1.5">
                                  {(res.assignments ?? []).map((a) => (
                                    <span
                                      key={a.id}
                                      className={cn(
                                        'inline-flex items-center gap-1 px-2 py-1 rounded-md text-[11px] font-bold',
                                        a.type === 'pool'
                                          ? 'bg-secondary/10 text-secondary'
                                          : 'bg-primary/10 text-primary',
                                      )}
                                    >
                                      {a.type === 'pool' ? '🗂️' : '👤'} {a.name}
                                    </span>
                                  ))}
                                </div>
                              </div>
                            )}
                          </div>
                        ))}
                      </div>
                    )}
                    {phase.key === 'recovery' && phase.icuProbability != null && (
                      <div className="mt-5 p-4 bg-white rounded-lg border border-slate-100">
                        <div className="flex items-center justify-between mb-2 gap-3 flex-wrap">
                          <span className="text-xs font-bold uppercase tracking-wider text-secondary">
                            ICU probability
                          </span>
                          <span className="text-sm font-black text-secondary">{phase.icuProbability}%</span>
                        </div>
                        <div className="w-full h-2 rounded-full bg-slate-100 overflow-hidden">
                          <div
                            className="h-full rounded-full bg-gradient-to-r from-secondary/30 to-secondary transition-all"
                            style={{ width: `${phase.icuProbability}%` }}
                          />
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </section>
        </div>

        {/* Right column */}
        <div className="lg:col-span-4 space-y-8">
          {/* Case info */}
          <aside className="bg-gradient-to-br from-primary to-primary-container rounded-2xl p-7 text-on-primary shadow-xl shadow-primary/20 overflow-hidden relative">
            <div className="absolute -right-8 -bottom-8 w-32 h-32 bg-white/10 rounded-full blur-2xl" />
            <div className="relative z-10">
              <p className="text-[10px] font-black uppercase tracking-widest text-white/70 mb-2">Case reference</p>
              <p className="font-mono text-2xl font-extrabold mb-6">{referenceCode}</p>
              <div className="space-y-4">
                <div className="flex items-center justify-between border-b border-white/15 pb-3">
                  <span className="text-sm text-white/70 font-medium">Overall status</span>
                  <span className="text-sm font-bold capitalize">{statusLabel[status]}</span>
                </div>
                <div className="flex items-center justify-between border-b border-white/15 pb-3">
                  <span className="text-sm text-white/70 font-medium">Est. duration</span>
                  <span className="text-sm font-bold">{formatMinutesToTime(totalDurationMinutes)}</span>
                </div>
                <div className="flex items-center justify-between border-b border-white/15 pb-3">
                  <span className="text-sm text-white/70 font-medium">Priority</span>
                  <span className="text-sm font-bold capitalize">{priorityLabel(data.priority)}</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm text-white/70 font-medium">Shortages</span>
                  <span className={cn(
                    'text-sm font-bold',
                    shortages.length > 0 ? 'text-amber-200' : 'text-emerald-200',
                  )}>
                    {shortages.length > 0 ? `${shortages.length} items low` : 'All in stock'}
                  </span>
                </div>
              </div>
            </div>
          </aside>

          {/* Supplies */}
          <section className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden">
            <div className="px-6 py-5 border-b border-slate-100 bg-surface-container-lowest/50">
              <div className="flex items-center gap-3">
                <span className="w-9 h-9 rounded-lg bg-secondary/10 flex items-center justify-center shrink-0">
                  <Library className="text-secondary" size={18} />
                </span>
                <div>
                  <h2 className="text-lg font-bold tracking-tight text-on-surface font-headline">Supplies & Stock</h2>
                  <p className="text-xs text-slate-500 mt-0.5">
                    Non-renewable items required for this procedure.
                  </p>
                </div>
              </div>
            </div>
            <div className="p-2">
              {data.resources.length === 0 ? (
                <p className="p-6 text-sm text-slate-400 italic text-center">No supply items on this request.</p>
              ) : (
                <ul className="divide-y divide-slate-50">
                  {data.resources.map((item) => (
                    <li key={item.id} className="px-5 py-4 hover:bg-slate-50/50 transition-colors">
                      <div className="flex items-start justify-between gap-3">
                        <div className="flex items-start gap-3 min-w-0">
                          <div className="w-9 h-9 rounded-lg bg-blue-50 flex items-center justify-center shrink-0">
                            <ResourceIcon icon={item.icon} />
                          </div>
                          <div className="min-w-0">
                            <p className="text-sm font-semibold text-on-surface truncate">{item.name}</p>
                            <p className="text-[11px] text-slate-500 truncate mt-0.5">{item.type}</p>
                          </div>
                        </div>
                        <div className="text-right shrink-0">
                          <p className={cn(
                            'text-xs font-black',
                            item.status === 'shortage' ? 'text-error' : 'text-slate-700',
                          )}>
                            req {item.required} / stk {item.stockpile}
                          </p>
                          <p className={cn(
                            'text-[10px] font-bold uppercase tracking-wider mt-0.5',
                            item.status === 'available' ? 'text-tertiary' : 'text-error',
                          )}>
                            {item.status}
                          </p>
                        </div>
                      </div>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}
