import { useMemo } from 'react';
import {
  Activity,
  AlertTriangle,
  Calendar,
  CalendarDays,
  CheckCircle2,
  ChevronRight,
  Clock,
  Droplets,
  Edit3,
  Library,
  Package,
  Stethoscope,
  Syringe,
  Thermometer,
  User,
  Users,
  Wrench,
  XCircle,
  FileText,
  ArrowLeft,
} from 'lucide-react';
import { cn } from '../../lib/utils';
import type {
  Priority,
  SurgeryRequestRecord,
  SurgeryRequestStatus,
} from '../../types/surgery';

type DetailViewProps = {
  record: SurgeryRequestRecord;
  onBack: () => void;
  onEdit: () => void;
};

const statusStyles: Record<SurgeryRequestStatus, string> = {
  DRAFT: 'text-slate-600',
  ESTIMATED: 'text-amber-600',
  PLANNING: 'text-blue-600',
  PLANNED: 'text-emerald-600',
  IN_PROGRESS: 'text-indigo-600',
  DONE: 'text-emerald-700',
  CANCELLED: 'text-rose-600',
};

const statusBadgeStyles: Record<SurgeryRequestStatus, string> = {
  DRAFT: 'bg-slate-100 text-slate-700',
  ESTIMATED: 'bg-amber-100 text-amber-700',
  PLANNING: 'bg-blue-100 text-blue-700',
  PLANNED: 'bg-emerald-100 text-emerald-700',
  IN_PROGRESS: 'bg-indigo-100 text-indigo-700',
  DONE: 'bg-emerald-200 text-emerald-800',
  CANCELLED: 'bg-rose-100 text-rose-700',
};

const statusLabel: Record<SurgeryRequestStatus, string> = {
  DRAFT: 'Draft',
  ESTIMATED: 'Estimated',
  PLANNING: 'Planning in progress',
  PLANNED: 'Planned & scheduled',
  IN_PROGRESS: 'Currently ongoing',
  DONE: 'Completed',
  CANCELLED: 'Cancelled',
};

const statusDescription: Record<SurgeryRequestStatus, string> = {
  DRAFT: 'This request has been saved as a draft and is not yet submitted for planning.',
  ESTIMATED: 'The request has been submitted and is queued for optimization and scheduling.',
  PLANNING: 'The solver is currently processing this request to find the optimal schedule.',
  PLANNED: 'An operating slot and resource assignments have been generated by the solver.',
  IN_PROGRESS: 'This surgery is currently being performed in the operating room.',
  DONE: 'The surgery has been completed successfully.',
  CANCELLED: 'This request has been cancelled and will not be scheduled.',
};

function priorityLabel(p: Priority): string {
  if (p === 'emergency') return 'Emergency';
  if (p === 'mandatory') return 'Mandatory';
  return 'Elective';
}

function formatDateTime(iso?: string): string {
  if (!iso) return '—';
  try {
    const d = new Date(iso);
    if (Number.isNaN(d.getTime())) return iso;
    return new Intl.DateTimeFormat(undefined, {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    }).format(d);
  } catch {
    return iso;
  }
}

function formatDateOnly(iso?: string): string {
  if (!iso) return '—';
  try {
    const d = new Date(iso + 'T12:00:00');
    if (Number.isNaN(d.getTime())) return iso;
    return new Intl.DateTimeFormat(undefined, {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    }).format(d);
  } catch {
    return iso;
  }
}

function formatMinutesToTime(minutes: number): string {
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  return `${h}:${m.toString().padStart(2, '0')}`;
}

function ResourceIcon({ icon }: { icon: string }) {
  if (icon === 'meds') return <Syringe className="text-secondary" size={18} />;
  if (icon === 'blood') return <Droplets className="text-secondary" size={18} />;
  if (icon === 'kit') return <Wrench className="text-secondary" size={18} />;
  if (icon === 'supply') return <Package className="text-secondary" size={18} />;
  return <Thermometer className="text-secondary" size={18} />;
}

function parseDurationToMinutes(duration: string): number {
  let total = 0;
  const dayMatch = duration.match(/(\d+)\s*day/);
  const hourMatch = duration.match(/(\d+)\s*hr/);
  const minMatch = duration.match(/(\d+)\s*min/);
  if (dayMatch) total += parseInt(dayMatch[1], 10) * 24 * 60;
  if (hourMatch) total += parseInt(hourMatch[1], 10) * 60;
  if (minMatch) total += parseInt(minMatch[1], 10);
  return total;
}

type PhaseMeta = {
  key: 'preOp' | 'operative' | 'postOp' | 'sterilization' | 'recovery';
  label: string;
  description: string;
  accent: string;
};

const PHASE_META: PhaseMeta[] = [
  { key: 'preOp', label: 'Pre-operative', description: 'Initial stabilization and vitals monitoring before the procedure.', accent: 'bg-secondary-container/15 border-secondary-container/40' },
  { key: 'operative', label: 'Operative', description: 'Core surgical procedure and anesthesia administration.', accent: 'bg-primary-container/10 border-primary-container/30' },
  { key: 'postOp', label: 'Post-operative', description: 'Emergence from anesthesia and initial recovery.', accent: 'bg-tertiary-container/15 border-tertiary-container/40' },
  { key: 'sterilization', label: 'Sterilization & Turnover', description: 'Room cleanup and sterilization between surgeries.', accent: 'bg-surface-container-lowest border-outline-variant/60' },
  { key: 'recovery', label: 'Recovery', description: 'Extended post-surgical care and patient monitoring.', accent: 'bg-secondary/5 border-secondary/20' },
];

export function SurgeryRequestDetailView({ record, onBack, onEdit }: DetailViewProps) {
  const { data, status, planResult, referenceCode, updatedAt } = record;

  const shortages = useMemo(() => data.resources.filter((r) => r.status === 'shortage'), [data.resources]);

  const phaseSummaries = useMemo(() => {
    const phaseOrder: PhaseMeta['key'][] = ['preOp', 'operative', 'postOp', 'sterilization', 'recovery'];
    let cumulativeOffset = 0;
    return phaseOrder.map((phaseKey) => {
      const meta = PHASE_META.find((m) => m.key === phaseKey)!;
      const phase = data.phases[phaseKey];
      const durationMinutes = parseDurationToMinutes(phase.duration);
      const startOffset = cumulativeOffset;
      cumulativeOffset += durationMinutes;
      return {
        ...meta,
        duration: phase.duration,
        durationMinutes,
        startOffset,
        resources: phase.resources,
        icuProbability: phase.icuProbability,
      };
    });
  }, [data.phases]);

  const totalDurationMinutes = phaseSummaries.reduce((acc, ph) => acc + ph.durationMinutes, 0);

  const hasPlanResult = Boolean(planResult && (planResult.result?.planned_start || planResult.result?.resources_assigned));
  const plannedStartIso = planResult?.result?.planned_start as string | undefined;
  const resourcesAssigned = (planResult?.result?.resources_assigned ?? {}) as Record<string, unknown>;
  const assignedEntries = Object.entries(resourcesAssigned);

  return (
    <div className="min-h-[calc(100vh-7rem)] pb-16">
      {/* Sticky Header */}
      <div className="sticky top-0 z-40 bg-surface-container-lowest/95 backdrop-blur border-b border-slate-200 mb-8 -mx-6 lg:-mx-8 px-6 lg:px-8 pt-6 pb-6">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div className="flex items-center gap-4 flex-wrap">
            <button
              type="button"
              onClick={onBack}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-white border border-slate-200 text-slate-700 text-sm font-bold hover:bg-slate-50 transition-colors"
            >
              <ArrowLeft size={16} />
              Back to list
            </button>
            <div className="flex items-center gap-1.5 text-sm text-slate-500 font-medium">
              <span>Surgery requests</span>
              <ChevronRight size={14} />
              <span className="text-on-surface font-semibold">Request details</span>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <span className={cn(
              'inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold uppercase tracking-wider',
              statusBadgeStyles[status],
            )}>
              <span className={cn(
                'w-1.5 h-1.5 rounded-full',
                (status === 'PLANNING' || status === 'IN_PROGRESS') && 'animate-pulse',
                status === 'DRAFT' && 'bg-slate-600',
                status === 'ESTIMATED' && 'bg-amber-600',
                status === 'PLANNING' && 'bg-blue-600',
                status === 'PLANNED' && 'bg-emerald-600',
                status === 'IN_PROGRESS' && 'bg-indigo-600',
                status === 'DONE' && 'bg-emerald-700',
                status === 'CANCELLED' && 'bg-rose-600',
              )} />
              {statusLabel[status]}
            </span>
            <button
              type="button"
              onClick={onEdit}
              disabled={status === 'CANCELLED'}
              className={cn(
                'inline-flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-bold transition-colors shadow-sm',
                status === 'CANCELLED'
                  ? 'bg-slate-100 text-slate-400 cursor-not-allowed'
                  : 'bg-primary text-on-primary hover:opacity-90 shadow-primary/20',
              )}
            >
              <Edit3 size={16} />
              {status === 'DRAFT' ? 'Continue editing' : 'Edit request'}
            </button>
          </div>
        </div>

        {/* Title row */}
        <div className="mt-6 flex flex-wrap items-end justify-between gap-6">
          <div className="min-w-0">
            <div className="flex items-center gap-3 mb-2 flex-wrap">
              <h1 className="text-3xl font-extrabold tracking-tight text-on-surface font-headline truncate">
                {data.patientName?.trim() || 'Unnamed patient'}
              </h1>
              <span className="text-xs font-mono font-bold bg-surface-container px-2 py-1 rounded text-outline">
                {referenceCode}
              </span>
            </div>
            <p className="text-slate-600 font-medium">
              {data.operationType?.trim() || 'Procedure not specified'}
              {data.primarySurgeon?.trim() ? ` • ${data.primarySurgeon}` : ''}
            </p>
          </div>
          <div className="text-sm text-slate-500">
            Last updated <span className="font-semibold text-on-surface">{formatDateTime(updatedAt)}</span>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 max-w-7xl mx-auto">
        {/* Left column */}
        <div className="lg:col-span-8 space-y-8">
          {/* Plan Results Banner */}
          {hasPlanResult && (
            <section className="bg-gradient-to-br from-emerald-50 via-white to-emerald-50 border-2 border-emerald-200 rounded-2xl p-8 shadow-sm overflow-hidden relative">
              <div className="absolute top-0 right-0 w-40 h-40 bg-emerald-100/40 rounded-full -translate-y-1/2 translate-x-1/3 blur-3xl" />
              <div className="relative z-10 flex items-start gap-4 flex-wrap">
                <div className="w-12 h-12 rounded-xl bg-emerald-500 text-white flex items-center justify-center shrink-0 shadow-lg shadow-emerald-500/30">
                  <CalendarDays size={24} />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1 flex-wrap">
                    <h2 className="text-xl font-bold text-emerald-900 font-headline">Scheduling Result</h2>
                    <span className="text-[10px] font-bold uppercase tracking-wider bg-emerald-100 text-emerald-700 px-2 py-0.5 rounded">
                      {statusLabel[status]}
                    </span>
                  </div>
                  <p className="text-sm text-emerald-800/80 font-medium mb-4">
                    The solver has produced an optimized schedule for this request.
                  </p>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="bg-white rounded-xl border border-emerald-100 p-5">
                      <p className="text-[10px] font-bold uppercase tracking-wider text-emerald-700/70 mb-2">
                        Assigned start time
                      </p>
                      <p className="text-2xl font-extrabold text-emerald-900 font-headline">
                        {formatDateTime(plannedStartIso)}
                      </p>
                      {plannedStartIso && (
                        <p className="text-xs text-emerald-800/70 mt-1 font-medium">
                          Expected end ~ {formatDateTime(new Date(new Date(plannedStartIso).getTime() + totalDurationMinutes * 60 * 1000).toISOString())}
                        </p>
                      )}
                    </div>
                    <div className="bg-white rounded-xl border border-emerald-100 p-5">
                      <p className="text-[10px] font-bold uppercase tracking-wider text-emerald-700/70 mb-2">
                        Role assignments ({assignedEntries.length})
                      </p>
                      {assignedEntries.length === 0 ? (
                        <p className="text-sm text-emerald-800/70 font-medium">No role assignments available.</p>
                      ) : (
                        <div className="flex flex-wrap gap-1.5">
                          {assignedEntries.slice(0, 12).map(([role, value]) => (
                            <span key={role} className="inline-flex items-center gap-1 px-2 py-1 rounded-md bg-emerald-50 text-emerald-800 text-xs font-bold border border-emerald-100">
                              <Users size={10} />
                              {String(role).replace(/_/g, ' ')}: {String(value)}
                            </span>
                          ))}
                          {assignedEntries.length > 12 && (
                            <span className="px-2 py-1 rounded-md text-xs font-bold text-emerald-800/70">
                              +{assignedEntries.length - 12} more
                            </span>
                          )}
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              </div>
            </section>
          )}

          {/* Status summary */}
          {!hasPlanResult && (
            <section className={cn(
              'rounded-2xl p-6 flex items-start gap-4 border',
              status === 'CANCELLED' ? 'bg-rose-50 border-rose-200' : 'bg-surface-container-low border-surface-container-high',
            )}>
              {status === 'CANCELLED' ? (
                <XCircle className="text-rose-600 shrink-0" size={28} />
              ) : status === 'PLANNING' ? (
                <div className="relative shrink-0">
                  <Activity className="text-blue-600 animate-pulse" size={28} />
                </div>
              ) : status === 'DRAFT' ? (
                <FileText className="text-slate-500 shrink-0" size={28} />
              ) : (
                <Clock className={cn('shrink-0', statusStyles[status])} size={28} />
              )}
              <div>
                <h3 className={cn('font-bold text-lg', status === 'CANCELLED' ? 'text-rose-900' : 'text-on-surface')}>
                  {statusLabel[status]}
                </h3>
                <p className={cn('text-sm mt-1', status === 'CANCELLED' ? 'text-rose-800/80' : 'text-outline')}>
                  {statusDescription[status]}
                </p>
              </div>
            </section>
          )}

          {/* Patient & Scheduling */}
          <section className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden">
            <div className="px-8 py-6 border-b border-slate-100 bg-surface-container-lowest/50">
              <div className="flex items-center gap-3">
                <span className="w-10 h-10 rounded-xl bg-primary-container/25 flex items-center justify-center shrink-0">
                  <User className="text-primary" size={22} />
                </span>
                <div>
                  <h2 className="text-xl font-bold tracking-tight text-on-surface font-headline">Patient & Scheduling</h2>
                  <p className="text-sm text-slate-500 mt-0.5">Identity, oversight, and time-window constraints.</p>
                </div>
              </div>
            </div>
            <div className="p-8">
              <dl className="grid grid-cols-1 md:grid-cols-2 gap-x-12 gap-y-8">
                <div>
                  <dt className="text-[11px] font-black uppercase tracking-widest text-slate-400 mb-1.5">Patient name</dt>
                  <dd className="text-lg font-semibold text-on-surface">{data.patientName?.trim() || '—'}</dd>
                </div>
                <div>
                  <dt className="text-[11px] font-black uppercase tracking-widest text-slate-400 mb-1.5">Procedure</dt>
                  <dd className="text-lg font-semibold text-on-surface">{data.operationType?.trim() || '—'}</dd>
                </div>
                <div>
                  <dt className="text-[11px] font-black uppercase tracking-widest text-slate-400 mb-1.5">Attending surgeon</dt>
                  <dd className="text-lg font-semibold text-on-surface">{data.primarySurgeon?.trim() || '—'}</dd>
                </div>
                <div>
                  <dt className="text-[11px] font-black uppercase tracking-widest text-slate-400 mb-1.5">Department</dt>
                  <dd className="text-lg font-semibold text-on-surface">{data.department?.trim() || '—'}</dd>
                </div>
                <div>
                  <dt className="text-[11px] font-black uppercase tracking-widest text-slate-400 mb-1.5">Priority</dt>
                  <dd>
                    <span className={cn(
                      'inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold',
                      data.priority === 'emergency' && 'bg-error-container text-on-error-container',
                      data.priority === 'mandatory' && 'bg-secondary-container/30 text-secondary',
                      data.priority === 'elective' && 'bg-surface-container-high text-on-surface-variant',
                    )}>
                      {data.priority === 'emergency' && <AlertTriangle size={12} />}
                      {priorityLabel(data.priority)}
                    </span>
                  </dd>
                </div>
                <div>
                  <dt className="text-[11px] font-black uppercase tracking-widest text-slate-400 mb-1.5">Infection status</dt>
                  <dd className="text-lg font-semibold text-on-surface flex items-center gap-2">
                    <CheckCircle2 className="text-tertiary shrink-0" size={18} />
                    {data.infectionStatus || 'Not specified'}
                  </dd>
                </div>
                <div className="md:col-span-2 bg-surface-container-low rounded-xl p-5 border border-surface-container-high">
                  <div className="flex items-center gap-2 mb-3">
                    <Calendar className="text-slate-500" size={18} />
                    <span className="text-[11px] font-black uppercase tracking-widest text-slate-500">Optimal time window</span>
                  </div>
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                    <div className="bg-white rounded-lg p-4 border border-slate-100">
                      <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-1">Earliest</p>
                      <p className="text-lg font-bold text-on-surface">{formatDateOnly(data.earliestDate)}</p>
                      <p className="text-xs text-slate-500 mt-0.5">{data.earliestDateTime?.split('T')[1] || '00:00'}</p>
                    </div>
                    <div className="flex items-center justify-center text-slate-300">
                      <div className="flex items-center gap-2">
                        <div className="h-0.5 w-8 bg-slate-200 rounded" />
                        <ChevronRight size={16} />
                        <div className="h-0.5 w-8 bg-slate-200 rounded" />
                      </div>
                    </div>
                    <div className="bg-white rounded-lg p-4 border border-rose-100">
                      <p className="text-[10px] font-bold uppercase tracking-wider text-rose-500 mb-1">Deadline</p>
                      <p className="text-lg font-bold text-rose-900">{formatDateOnly(data.endDate)}</p>
                      <p className="text-xs text-rose-500/80 mt-0.5">{data.endDateTime?.split('T')[1] || '23:59'}</p>
                    </div>
                  </div>
                </div>
              </dl>
            </div>
          </section>

          {/* Phase Resource Configuration */}
          <section className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden">
            <div className="px-8 py-6 border-b border-slate-100 bg-surface-container-lowest/50">
              <div className="flex items-center justify-between gap-4 flex-wrap">
                <div className="flex items-center gap-3">
                  <span className="w-10 h-10 rounded-xl bg-primary-container/25 flex items-center justify-center shrink-0">
                    <Activity className="text-primary" size={22} />
                  </span>
                  <div>
                    <h2 className="text-xl font-bold tracking-tight text-on-surface font-headline">Phase Resource Configuration</h2>
                    <p className="text-sm text-slate-500 mt-0.5">
                      Staff, rooms, and equipment across the surgical lifecycle.
                      Total estimated duration: <span className="font-bold text-on-surface">{totalDurationMinutes} min ({formatMinutesToTime(totalDurationMinutes)})</span>
                    </p>
                  </div>
                </div>
              </div>
            </div>

            {/* Timeline strip */}
            <div className="px-8 py-6 bg-surface-container-lowest/30 border-b border-slate-100">
              <div className="relative h-4 rounded-full bg-surface-container-high overflow-hidden flex">
                {phaseSummaries.map((phase) => {
                  const pct = totalDurationMinutes > 0 ? (phase.durationMinutes / totalDurationMinutes) * 100 : 20;
                  const color =
                    phase.key === 'preOp' ? 'bg-secondary-container' :
                    phase.key === 'operative' ? 'bg-primary' :
                    phase.key === 'postOp' ? 'bg-tertiary-container' :
                    phase.key === 'sterilization' ? 'bg-outline-variant' :
                    'bg-secondary/70';
                  return (
                    <div
                      key={phase.key}
                      className={cn('h-full first:rounded-l-full last:rounded-r-full', color)}
                      style={{ width: `${pct}%` }}
                      title={`${phase.label} — ${phase.duration}`}
                    />
                  );
                })}
              </div>
              <div className="grid grid-cols-5 gap-2 mt-3">
                {phaseSummaries.map((phase) => (
                  <div key={phase.key} className="flex items-center gap-2 min-w-0">
                    <span className={cn(
                      'w-2.5 h-2.5 rounded shrink-0',
                      phase.key === 'preOp' ? 'bg-secondary-container' :
                      phase.key === 'operative' ? 'bg-primary' :
                      phase.key === 'postOp' ? 'bg-tertiary-container' :
                      phase.key === 'sterilization' ? 'bg-outline-variant' :
                      'bg-secondary/70',
                    )} />
                    <span className="text-[10px] font-bold text-slate-600 truncate">{phase.label}</span>
                  </div>
                ))}
              </div>
            </div>

            <div className="p-8 space-y-5">
              {phaseSummaries.map((phase) => (
                <div
                  key={phase.key}
                  className={cn(
                    'rounded-xl border overflow-hidden',
                    phase.accent,
                  )}
                >
                  <div className="px-6 py-4 flex flex-wrap items-center justify-between gap-3 border-b border-black/5">
                    <div>
                      <div className="flex items-center gap-2">
                        <h3 className="font-bold text-on-surface">{phase.label}</h3>
                        <span className="text-[10px] font-bold uppercase tracking-wider text-outline/70 bg-white/70 px-2 py-0.5 rounded border border-black/5">
                          Phase starts at T+{formatMinutesToTime(phase.startOffset)}
                        </span>
                      </div>
                      <p className="text-xs text-slate-600 mt-0.5">{phase.description}</p>
                    </div>
                    <div className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white border border-black/5">
                      <Clock size={14} className="text-slate-500" />
                      <span className="text-sm font-bold text-on-surface">{phase.duration}</span>
                    </div>
                  </div>
                  <div className="px-6 py-5 bg-white/40">
                    {phase.resources.length === 0 ? (
                      <p className="text-sm text-slate-400 italic">No resources configured for this phase.</p>
                    ) : (
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                        {phase.resources.map((res, idx) => (
                          <div
                            key={`${phase.key}-${idx}-${res.name}`}
                            className="bg-white rounded-lg border border-slate-100 p-4 hover:shadow-sm transition-shadow"
                          >
                            <div className="flex items-start justify-between gap-3">
                              <div className="flex items-start gap-3 min-w-0">
                                <div className="w-9 h-9 rounded-lg bg-tertiary-container/15 text-tertiary flex items-center justify-center shrink-0">
                                  <Stethoscope size={16} />
                                </div>
                                <div className="min-w-0">
                                  <p className="font-bold text-sm text-on-surface truncate">{res.name}</p>
                                  {res.roles && res.roles.length > 0 && res.roles[0] !== res.name && (
                                    <p className="text-[11px] text-slate-500 mt-0.5">
                                      Role: {res.roles.join(', ')}
                                    </p>
                                  )}
                                </div>
                              </div>
                              <span className="text-sm font-black px-2.5 py-1 rounded-md bg-primary/10 text-primary shrink-0">
                                ×{res.count}
                              </span>
                            </div>
                            <div className="mt-3 pt-3 border-t border-slate-100/70 flex items-center justify-between">
                              <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">
                                Required window
                              </span>
                              <span className="text-xs font-bold text-on-surface-variant">
                                T+{formatMinutesToTime(res.startTime ?? 0)} — T+{formatMinutesToTime(res.endTime ?? phase.durationMinutes)}
                              </span>
                            </div>
                            {(res.assignments ?? []).length > 0 && (
                              <div className="mt-3 pt-3 border-t border-slate-100/70">
                                <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-2 block">
                                  Manual assignments
                                </span>
                                <div className="flex flex-wrap gap-1.5">
                                  {(res.assignments ?? []).map((a) => (
                                    <span
                                      key={a.id}
                                      className={cn(
                                        'inline-flex items-center gap-1 px-2 py-1 rounded-md text-[11px] font-bold',
                                        a.type === 'pool'
                                          ? 'bg-secondary/10 text-secondary'
                                          : 'bg-primary/10 text-primary',
                                      )}
                                    >
                                      {a.type === 'pool' ? '🗂️' : '👤'} {a.name}
                                    </span>
                                  ))}
                                </div>
                              </div>
                            )}
                          </div>
                        ))}
                      </div>
                    )}
                    {phase.key === 'recovery' && phase.icuProbability != null && (
                      <div className="mt-5 p-4 bg-white rounded-lg border border-slate-100">
                        <div className="flex items-center justify-between mb-2 gap-3 flex-wrap">
                          <span className="text-xs font-bold uppercase tracking-wider text-secondary">
                            ICU probability
                          </span>
                          <span className="text-sm font-black text-secondary">{phase.icuProbability}%</span>
                        </div>
                        <div className="w-full h-2 rounded-full bg-slate-100 overflow-hidden">
                          <div
                            className="h-full rounded-full bg-gradient-to-r from-secondary/30 to-secondary transition-all"
                            style={{ width: `${phase.icuProbability}%` }}
                          />
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </section>
        </div>

        {/* Right column */}
        <div className="lg:col-span-4 space-y-8">
          {/* Case info */}
          <aside className="bg-gradient-to-br from-primary to-primary-container rounded-2xl p-7 text-on-primary shadow-xl shadow-primary/20 overflow-hidden relative">
            <div className="absolute -right-8 -bottom-8 w-32 h-32 bg-white/10 rounded-full blur-2xl" />
            <div className="relative z-10">
              <p className="text-[10px] font-black uppercase tracking-widest text-white/70 mb-2">Case reference</p>
              <p className="font-mono text-2xl font-extrabold mb-6">{referenceCode}</p>
              <div className="space-y-4">
                <div className="flex items-center justify-between border-b border-white/15 pb-3">
                  <span className="text-sm text-white/70 font-medium">Overall status</span>
                  <span className="text-sm font-bold capitalize">{statusLabel[status]}</span>
                </div>
                <div className="flex items-center justify-between border-b border-white/15 pb-3">
                  <span className="text-sm text-white/70 font-medium">Est. duration</span>
                  <span className="text-sm font-bold">{formatMinutesToTime(totalDurationMinutes)}</span>
                </div>
                <div className="flex items-center justify-between border-b border-white/15 pb-3">
                  <span className="text-sm text-white/70 font-medium">Priority</span>
                  <span className="text-sm font-bold capitalize">{priorityLabel(data.priority)}</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm text-white/70 font-medium">Shortages</span>
                  <span className={cn(
                    'text-sm font-bold',
                    shortages.length > 0 ? 'text-amber-200' : 'text-emerald-200',
                  )}>
                    {shortages.length > 0 ? `${shortages.length} items low` : 'All in stock'}
                  </span>
                </div>
              </div>
            </div>
          </aside>

          {/* Supplies */}
          <section className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden">
            <div className="px-6 py-5 border-b border-slate-100 bg-surface-container-lowest/50">
              <div className="flex items-center gap-3">
                <span className="w-9 h-9 rounded-lg bg-secondary/10 flex items-center justify-center shrink-0">
                  <Library className="text-secondary" size={18} />
                </span>
                <div>
                  <h2 className="text-lg font-bold tracking-tight text-on-surface font-headline">Supplies & Stock</h2>
                  <p className="text-xs text-slate-500 mt-0.5">
                    Non-renewable items required for this procedure.
                  </p>
                </div>
              </div>
            </div>
            <div className="p-2">
              {data.resources.length === 0 ? (
                <p className="p-6 text-sm text-slate-400 italic text-center">No supply items on this request.</p>
              ) : (
                <ul className="divide-y divide-slate-50">
                  {data.resources.map((item) => (
                    <li key={item.id} className="px-5 py-4 hover:bg-slate-50/50 transition-colors">
                      <div className="flex items-start justify-between gap-3">
                        <div className="flex items-start gap-3 min-w-0">
                          <div className="w-9 h-9 rounded-lg bg-blue-50 flex items-center justify-center shrink-0">
                            <ResourceIcon icon={item.icon} />
                          </div>
                          <div className="min-w-0">
                            <p className="text-sm font-semibold text-on-surface truncate">{item.name}</p>
                            <p className="text-[11px] text-slate-500 truncate mt-0.5">{item.type}</p>
                          </div>
                        </div>
                        <div className="text-right shrink-0">
                          <p className={cn(
                            'text-xs font-black',
                            item.status === 'shortage' ? 'text-error' : 'text-slate-700',
                          )}>
                            req {item.required} / stk {item.stockpile}
                          </p>
                          <p className={cn(
                            'text-[10px] font-bold uppercase tracking-wider mt-0.5',
                            item.status === 'available' ? 'text-tertiary' : 'text-error',
                          )}>
                            {item.status}
                          </p>
                        </div>
                      </div>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          </section>

          {/* Solver Info */}
          <section className="bg-surface-container-low rounded-2xl border border-surface-container-high p-6">
            <h3 className="font-bold text-sm text-on-surface-variant uppercase tracking-wider mb-4 flex items-center gap-2">
              <Activity size={16} />
              Backend integration note
            </h3>
            <p className="text-xs text-outline leading-relaxed mb-4">
              When you submit, this request is marked <span className="font-mono font-bold bg-white px-1.5 py-0.5 rounded text-primary">ESTIMATED</span> and
              becomes eligible for the planning pipeline. The solver assigns a concrete start time in
              <code className="font-mono text-xs bg-white px-1.5 py-0.5 rounded mx-1">time_windows.planned_start</code>
              and promotes status to <span className="font-mono font-bold bg-white px-1.5 py-0.5 rounded text-emerald-700">PLANNED</span>.
            </p>
            <div className="space-y-2 text-xs">
              {[
                ['DRAFT', 'Saved locally, not queued for planning'],
                ['ESTIMATED', 'Submitted, waiting to be optimized'],
                ['PLANNING', 'Included in active solver payload'],
                ['PLANNED', 'Solver returned concrete schedule'],
                ['IN_PROGRESS / DONE', 'Time-tracked by the scheduler'],
              ].map(([s, desc]) => (
                <div key={s} className="flex items-start gap-2">
                  <span className={cn(
                    'font-mono text-[10px] font-bold px-2 py-0.5 rounded shrink-0 mt-0.5',
                    statusBadgeStyles[s as SurgeryRequestStatus] ?? 'bg-slate-100 text-slate-600',
                  )}>
                    {s}
                  </span>
                  <span className="text-outline">{desc}</span>
                </div>
              ))}
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}
