from enum import IntEnum


class ShiftEnum(IntEnum):
    V = 0
    O = 1
    D = 2
    E = 3
    L = 4
    N = 5


class DaysOfWeekEnum(IntEnum):
    MONDAY = 0
    TUESDAY = 1
    WEDNESDAY = 2
    THURSDAY = 3
    FRIDAY = 4
    SATURDAY = 5
    SUNDAY = 6


class ConstraintEnum(IntEnum):
    IDENTICAL_SHIFT_TYPES_DURING_WEEKEND = 0
    COMPLETE_WEEKENDS = 1
    NO_NIGHT_SHIFT_BEFORE_FREE_WEEKEND = 2
    NO_FREE_DAY_BEFORE_WORKING_WEEKEND = 3
    MAX_NUM_ASSIGNMENTS = 4
    MIN_NUM_ASSIGNMENTS = 5
    MAX_CONSECUTIVE_WORKING_DAYS = 6
    MIN_CONSECUTIVE_WORKING_DAYS = 7
    MAX_CONSECUTIVE_FREE_DAYS = 8
    MIN_CONSECUTIVE_FREE_DAYS = 9
    MAX_CONSECUTIVE_WORKING_WEEKENDS = 10
    MIN_CONSECUTIVE_WORKING_WEEKENDS = 11
    LATE_FOLLOWED_DAY = 12
    DAY_FOLLOWED_EARLY_FOLLOWED_DAY = 13
    LATE_FOLLOWED_EARLY = 14
    LATE_FOLLOWED_NIGHT = 15
    DAY_FOLLOWED_NIGHT = 16
    NIGHT_FOLLOWED_DAY = 17
    NIGHT_FOLLOWED_EARLY = 18


CONSTRAINT_NAME_TO_TYPE = {m.name.lower(): m for m in ConstraintEnum}
